services:
  - type: web
    name: invoice-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn invoice_scanner_api:app --bind 0.0.0.0:$PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false 
      - key: PYTHON_VERSION
        value: 3.12.4
      - key: ENVIRONMENT
        value: production
      - key: SENTRY_DSN
        sync: false
      - key: CORS_ORIGINS
        value: https://chef-invoice-vision.vercel.app